config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'	
  resources :ideas
  # this function gets the about from the http response and the rocketsybmbol denotes to redirect to the static pages with action about
  get 'about' => 'static_pages#about'
  # this function takes the random and same working principle as above 
  get 'random' => 'static_pages#random'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	# validate the presence of the datas in the given fields in the database
	  validates :description, :author, presence: true
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	def index 
		# assiging the ideas object the all ideas table content from the datbase
		@ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 10 )
	end 

	def create 
    #creating a new create idea using the create function by hitting to the idea model 
		@ideas = Idea.create(idea_params)
     if @idea.valid?
      flash[:success] = "Your idea has been posted!"
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
    end
    redirect_to root_path

	end

  #editing the ideas by 

  def edit
    @idea = Idea.find(params[:id])
  end

  #updating our ideas field 

  def update 
    @ideas = Idea.find(params[:id])
    if @ideas.update( idea_params )
      flash[:success] = " The idea has been udpated"
      redirect_to root_path
    else
      flash[:alert] = " whoops error"
      redirect_to edit_idea_path(params[:id])
    end
  end
  
  #creating the destroy or delete for our ideator

  def destroy 
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:success] = "The idea was successfully deleted!"
    redirect_to root_path
  end

    # creating a encapsulation to prevent the external user from cracking the permission 

	private 

   #creating private space to whitelist the parameters

	def idea_params
		params.require(:idea).permit(:description, :author)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about

  end

  def random
  	@idea = Idea.order( "RANDOM ()").first 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>
<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<%= simple_form_for Idea.new do |f| %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
<% @ideas.each do |idea| %>
<div class="panel panel-default">
	<div class="panel-body">
		<blockquote>
			<p><%= idea.description %></p>
			<small>by <%= idea.author %></small>
		</blockquote>
		<br>
		<!-- 	here we are creating the delete link with the path described as the idea_path given and () idea is specifying which idea we are deleting the form plus the method is creating the delete method in the rails class is defining the button structure and the data is creating the pop up  -->
		<%= link_to 'Delete' , idea_path(idea) , method: :delete %>
		<%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
	</div>
</div>
<% end %>
<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id = "wrap">
      <%= render 'shared/nav' %>
      <div class = "container">
        <div class = "row">
          <div class = "col-xs-12 col-md-6 col-md-offset-3">
            <%= render 'shared/flash_messages' %>
            <%= yield %>
          </div>
          <div class="footer text-center">
            <%= render 'shared/foot' %>
          </div>
        </body>
      </html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_foot.html.erb
<!-- what we have done here is we created a render path in the application as shared foot then the content below is rendered below
-->
<!-- footer
-->  
<div class="footer text-center">
  <p>© JYAASA <%= Date.today.year %> All Rights Reserved</p>
</div>

app/views/shared/_nav.html.erb
<!-- what we have done here is we rendered the navbar into the <applet></applet>ication path
-->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">Ideator</a>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav navbar-right">
		<li><%= link_to 'All Ideas', root_path %></li>
		<li><%= link_to 'About', about_path %></li>
	</ul>
	</div><!-- /.navbar-collapse -->
</div>
<!-- navbar-header -->

app/views/static_pages/about.html.erb
<h1> Static pages are created in this sublime. There is nothing to add in the about me as we all know there are nothing much created </h1>

app/views/static_pages/random.html.erb
<h1> 
	Random Idea from the table
</h1>
<%= @idea.description %>
<%= @idea.author %>